apiVersion: v1
kind: Route
metadata:
  name: appname-https-public
  namespace: simon
spec:
  host: appname.demo.dfe.secnix.co.uk
  to:
    kind: Service
    name: appname
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
status:
  ingress:
    - host: appname.demo.dfe.secnix.co.uk
      routerName: router
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2017-10-27T18:27:41Z'
      wildcardPolicy: None

